name: Безперервна інтеграція

on:
  push:
  pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Завантаження репозиторію
        uses: actions/checkout@v4

      - name: Налаштування Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Встановлення залежностей
        run: pip install -r requirements.txt

      - name: Перевірка PEP8 через flake8
        run: flake8 .

      - name: Запуск тестів
        run: python -m pytest tests
